baseURL = 'https://steele-horse.com/'
languageCode = 'en-us'
title = "Steele Horse LLC"
theme = "hugo-coder"

paginate = 20

#[services]
#[services.disqus]
#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Jeremy Chalfant"
  info = "DevOps Engineer and Systems Administrator"
  description = "Jeremy Chalfant's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/logo1-inverted.png"
  #gravatar = "jeremy.chalfant@protonmail.com"

  faviconSVG = "/images/logo1-inverted-favico.svg"
  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/foobarbam/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/foobarbam"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  url = "https://www.linkedin.com/in/jeremy-c-107b5bb3/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Resume"
  weight = 3
  url = "resume/"